# .github/workflows/update-data.yml
name: Update Data

on:
  repository_dispatch:
    types: [data-update]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone data repo
        uses: actions/checkout@v4
        with:
          repository: cdracars/ebay_prusa_scrapper
          path: data-repo
          token: ${{ secrets.DATA_REPO_PAT }} # PAT with repo access

      - name: Copy data files
        run: |
          mkdir -p public/data
          cp -r data-repo/public/data/* public/data/

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data
          git commit -m "Update data files" || exit 0
          git push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build Next.js app
        run: yarn build
        env:
          NEXT_PUBLIC_BASE_PATH: /prusa-market-analysis

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
